service: helena-api

frameworkVersion: ">=1.1.0"

provider:
  name: aws
  profile: helena
  region: sa-east-1
  useDotenv: true
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: dialog-table
    WATSON_ASSISTANT_IAM_APIKEY: ${env:WATSON_ASSISTANT_IAM_APIKEY}
    WATSON_ASSISTANT_ID: ${env:WATSON_ASSISTANT_ID}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query

          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  dialog:
    handler: handlers/dialog.handler
    events:
      - http:
          path: /dialog
          method: post
          cors: true

  session:
    handler: handlers/session.handler
    events:
      - http:
          path: /session
          method: get
          cors: true

  list-by-intent:
    handler: handlers/list-by-intent.handler
    events:
      - http:
          path: /list
          method: get
          cors: true

resources:
  Resources:
    DialogDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: main_intent
            AttributeType: S
        KeySchema:
          - AttributeName: main_intent
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
